name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - run: npm install
      - run: npm run format
      - run: npm run lint
      #   - run: npm test
      - run: npm run build
