name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install pnpm
        run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run check
      - run: pnpm run build
      - run: pnpm run start
